name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Crear archivo .env desde secretos
        run: |
          echo "API_URL=${{ secrets.API_BASE_URL }}" >> .env
          echo "API_KEY=${{ secrets.API_KEYS }}" >> .env
          echo "EMOTIONS=${{ secrets.EMOTIONS }}" >> .env
          # Agrega aquí más variables según tu .env, excepto las que terminan en TEST

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk